parameters:
    admin_email: 'heinzcodeur@gmx.com'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\EventSubscriber\ExceptionSubscriber:
        tags:
            - { name: kernel.event_subscriber }
    App\EventSubscriber\RequestSubscriber:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $requestStack: '@request_stack'
            $logger: '@logger'
        tags:
            - { name: 'kernel.event_subscriber' }